version: "3"

services:
  mysql:
    image: mysql:8
    container_name: remindroute-mysql
    restart: always
    ports:
      - 3310:3310
    environment:
      MYSQL_TCP_PORT: 3310
      MYSQL_ROOT_PASSWORD: mysqlrootpw
      MYSQL_DATABASE: remindroute
    volumes:
      - ../../db:/docker-entrypoint-initdb.d