name: deploy_to_prod
on:
  push:
    branches: [ main ]

env:
  BUILD_PROFILE_OPTION: -Pprofile=prod
  AWS_SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
  DEPLOY_SERVER_HOST: ec2-44-201-161-53.compute-1.amazonaws.com
  DEPLOY_SERVER_USER: ec2-user
  DEPLOY_SERVER_DESTINATION: /home/ec2-user/app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew buildFatJar ${{ env.BUILD_PROFILE_OPTION }}

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.DEPLOY_SERVER_HOST }}
          username: ${{ env.DEPLOY_SERVER_USER }}
          key: ${{ env.AWS_SSH_PRIVATE_KEY }}
          source: "build/libs/remindroute.jar"
          target: ${{ env.DEPLOY_SERVER_DESTINATION }}
          rm: true

      - name: Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DEPLOY_SERVER_HOST }}
          username: ${{ env.DEPLOY_SERVER_USER }}
          key: ${{ env.AWS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.OCCUPY_SSH_PORT }}
          script: |
            killall java || true
            export AWS_S3_USER_ACCESS_KEY=${{ secrets.AWS_S3_USER_ACCESS_KEY }}
            export AWS_S3_USER_ACCESS_SECRET=${{ secrets.AWS_S3_USER_ACCESS_SECRET }}
            export SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
            export SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
            java -Duser.timezone="Asia/Seoul" -jar /home/ec2-user/app/build/libs/remindroute.jar > /dev/null &
